// <auto-generated />
using Duvido.GestãoDeGame.WEB_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Duvido.GestãoDeGame.WEB_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230908184059_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Duvido.GestãoDeGame.WEB_API.Models.ItensDaListaViewModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IDDaLista")
                        .HasColumnType("int");

                    b.Property<string>("NomeDoItem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Posicao")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDDaLista");

                    b.ToTable("ItensDaLista");
                });

            modelBuilder.Entity("Duvido.GestãoDeGame.WEB_API.Models.ListaViewModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeDaLista")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ID");

                    b.ToTable("Lista");
                });

            modelBuilder.Entity("Duvido.GestãoDeGame.WEB_API.Models.UsuarioViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Duvido.GestãoDeGame.WEB_API.Models.ItensDaListaViewModel", b =>
                {
                    b.HasOne("Duvido.GestãoDeGame.WEB_API.Models.ListaViewModel", null)
                        .WithMany("ItensDaLista")
                        .HasForeignKey("IDDaLista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Duvido.GestãoDeGame.WEB_API.Models.ListaViewModel", b =>
                {
                    b.Navigation("ItensDaLista");
                });
#pragma warning restore 612, 618
        }
    }
}
